"""empty message

Revision ID: 119790bb9987
Revises: bc7998422e43
Create Date: 2020-05-31 01:37:42.097026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119790bb9987'
down_revision = 'bc7998422e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'area_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'area_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
