"""empty message

Revision ID: 6300ecd92430
Revises: f2588aca48a2
Create Date: 2020-05-31 01:32:10.333042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6300ecd92430'
down_revision = 'f2588aca48a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Area', sa.Column('city', sa.String(), nullable=True))
    op.add_column('Area', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Area', 'state')
    op.drop_column('Area', 'city')
    # ### end Alembic commands ###
