"""empty message

Revision ID: bc7998422e43
Revises: 6300ecd92430
Create Date: 2020-05-31 01:36:27.185399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7998422e43'
down_revision = '6300ecd92430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'area_id')
    # ### end Alembic commands ###
