"""empty message

Revision ID: f2588aca48a2
Revises: c2323594a447
Create Date: 2020-05-31 01:31:52.580186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2588aca48a2'
down_revision = 'c2323594a447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Area', 'state')
    op.drop_column('Area', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Area', sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Area', sa.Column('state', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
